name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - maning-service
          - api-gateway
          - book-service
          - cambio-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Build with Maven
        run: |
          cd ${{ matrix.service }}
          ls -l
          mvn spring-boot:build-image -DskipTests

      - name: Build with Maven
        run: |
          cd ${{ matrix.service }}
          ls -l
          mvn spring-boot:build-image -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push Docker image (with tags)
        run: |
          IMAGE_NAME=ricardo1782/${{ matrix.service }}
          TAG=0.0.1-SNAPSHOT
          cd ${{ matrix.service }}
          docker build -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest
